version: '3.8'

services:

  node-server:
    build:
      context: ./ServEase-Nexus-BackEnd
    develop:
      watch:
        - action: rebuild
          path: ./ServEase-Nexus-BackEnd/package.json
    volumes:
      - ./ServEase-Nexus-BackEnd/dist:/app/dist
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - app-network 
    # depends_on:
    #   - mongodb
    # environment:
    #   MONGO_URI: mongodb://mongodb:27017/mydatabase
    command: nodemon --legacy-watch


  node-react:
    build:
      context: ./ServEase-Nexus-FrontEnd
    develop:
      watch:
      - action: rebuild
        path: ./ServEase-Nexus-FrontEnd/package.json
    tty: true
    volumes:
      - type: bind
        source: ./ServEase-Nexus-FrontEnd/src
        target: /app/src
    ports:
      - "7160:7160"
    networks:
      - app-network 
    depends_on:
      - node-server
    command: npm run dev

  postgres:
    image: postgres:15.5-bullseye
    volumes:
      - ./PostgresDB/data:/var/lib/postgresql/data
      - ./PostgresDB/init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

  # redis:
  #   image: redis:bookworm
  #   volumes:
  #     - ./redis_data:/data
  #   ports:
  #     - "6379:6379"


networks: 
  app-network: